default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: optica
  password: optica
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: optica_test

development:
  <<: *default
  database: optica_development

production:
  <<: *default
  database: optica_production
