default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: optica
  password: optica

test:
  <<: *default
  database: optica_test

development:
  <<: *default
  database: optica_production

production:
  <<: *default
  database: optica_production
