default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: optica
  host: localhost


test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: root
  password: '12452'

production:
  <<: *default
  username: optica
  password: '123546'

