default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: optica
  host: localhost

test:
  <<: *default
  database: optica_test
  username: root
  password: '12452'

development:
  <<: *default
  username: root
  password: '12452'

production:
  <<: *default
  username: optica
  password: '123546'

