theme: 'advanced'
mode: "textareas"
# :height => 100
# #:content_css => "/stylesheets/base.css"
# :remove_script_host => true
# :theme_advanced_toolbar_location => "top"
# :theme_advanced_toolbar_align => "left"
# :theme_advanced_buttons2 => %w{ spellchecker }
# :edito